### ISSUE TITLE
i cannot find the package of roi_align，how could i import thsi 

### ISSUE THREAD

**Issue by tengfeiliu** [shiyi-zh0408/LOGO#1]
![image](https://github.com/shiyi-zh0408/LOGO/assets/4695797/9b5576c7-b41d-4c15-8e5e-fa79fb4fc2c4)

**Comment by shiyi-zh0408** [comment]
Hi, you can download this package from https://github.com/longcw/RoIAlign.pytorch, thanks for your question!

**Comment by tengfeiliu** [comment]
got it. i'll have a try.  thanks a lot.
