### ISSUE TITLE
About dataset class for LOGO dataset

### ISSUE THREAD

**Issue by vvirgooo2** [shiyi-zh0408/LOGO#3]
I noticed that there are goat codes in 3 sub repos and corresponding codes for datasets MTL-AQA and AQA-7， but I can‘t find any data preprocessing code and PyTorch dataset code for LOGO. Do you have any plans to release this part of the code?  Looking forward to receiving your reply.

**Comment by shiyi-zh** [comment]
I'm sorry, our code was modified based on previous code, and the original files were not renamed when uploaded, causing confusion for you. The data preprocessing codes corresponding to the three methods are: MUSDL-GOAT/MTL-AQA/dataset.py, FineDiving-GOAT/datasets/FineDiving_Pair.py, and CoRe-GOAT/datasets/MTLPair.py. Thank you for bringing this issue to our attention!

**Comment by shiyi-zh** [comment]
> I noticed that there are goat codes in 3 sub repos and corresponding codes for datasets MTL-AQA and AQA-7， but I can‘t find any data preprocessing code and PyTorch dataset code for LOGO. Do you have any plans to release this part of the code? Looking forward to receiving your reply.

I'm sorry, our code was modified based on previous code, and the original files were not renamed when uploaded, causing confusion for you. The data preprocessing codes corresponding to the three methods are: MUSDL-GOAT/MTL-AQA/dataset.py, FineDiving-GOAT/datasets/FineDiving_Pair.py, and CoRe-GOAT/datasets/MTLPair.py. Thank you for bringing this issue to our attention!

**Comment by vvirgooo2** [comment]
thanks!
